cats_99/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats
end

cats_99/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats_99/app/models/cat.rb
require 'date'

class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper

  COLORS = [
    "Black",
    "White",
    "Spotted",
    "Yellow",
    "Tabby",
    "Brown",
    "Grey",
    "Rainbow"
  ]

  validates :birth_date, presence: true
  validates :color, presence: true, inclusion: { in: COLORS, message: "This color isn't right!" }
  validates :name, presence: true
  validates :sex, presence: true
  validates :description, presence: true


  has_many :cat_rental_requests,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest,
    dependent: :destroy

  def age
    Time.now.year - self.birth_date.year
  end


end

cats_99/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  STATUS = ['PENDING', 'APPROVED', 'DENIED']


  validates :status, presence: true, inclusion: { in: STATUS, message: 'That aint a status'}
  validates :cat_id, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true

  belongs_to :cat,
    foreign_key: :cat_id,
    class_name: :Cat


end

cats_99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cats_99/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def create
    cat = Cat.new(cat_params)

    if cat.save
      redirect_to cat_url(cat)
    else
      render json: cat.errors.full_messages, status: 422
    end
  end

  def new
    @cat = Cat.new
    render :new
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    cat = Cat.find(params[:id])

    if cat.update(cat_params)
      redirect_to cat_url(cat)
    else
      render json: cat.errors.full_messages, status: 422
    end
  end


  private

  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end
end

cats_99/app/helpers/application_helper.rb
module ApplicationHelper
end

cats_99/app/views/cats/_form.html.erb
<% if action == :new %>
  <% action_url = cats_url %>
  <% submit_value = "Build a Cat!" %>
<% elsif action == :edit %>
  <% action_url = cat_url(@cat) %>
  <% submit_value = "Fix a Cat!" %>
<% end %>

<form action="<%= action_url %>" method="post">
  <% if action == :edit %>
  <input type="hidden" name="_method" value="patch">
  <% end %>
  <label>
  Name:
  <input type="text" name="cat[name]" value="<%= cat.name %>">
  </label>
  <br>
  <br>
  <label>
  Birth Date:
  <input type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">
  </label>
  <br>
  <br>
  <label>
  Sex:
  <% if cat.sex == "M" %>
  <input type="radio" name="cat[sex]" value="M" checked>M
  <input type="radio" name="cat[sex]" value="F">F
  <% else %>
  <input type="radio" name="cat[sex]" value="M">M
  <input type="radio" name="cat[sex]" value="F" checked>F
  <% end %>
  </label>
  <br>
  <br>
  <label>
  Color:

  <select name="cat[color]">
    <% Cat::COLORS.each do |color| %>
     <% if cat.color == color %>
     <option selected value="<%= color %>"><%= color %></option>
     <% else %>
     <option value="<%= color %>"><%= color %></option>
     <% end %>
    <% end %>
  </select>

  </label>
  <br>
  <br>
  <label>
  Description:
  <br>
  <textarea rows = "4" cols = "50" name = "cat[description]"><%= cat.description %></textarea>
  </label>
  <br>
  <br>

  <input type="submit" name="" value="<%= submit_value %>">

</form>

cats_99/app/views/cats/edit.html.erb
<%= render 'form', cat: @cat, action: :edit %>

cats_99/app/views/cats/index.html.erb
<ul>
  <% @cats.each do |cat|%>
    <li>
      <ul>
        <li>Name: <%= cat.name %></li>
        <li>Birth Date: <%= cat.birth_date %></li>
        <li>Age: <%= cat.age %></li>
        <li>Color: <%= cat.color %></li>
        <li>Sex: <%= cat.sex%></li>
        <li>Description: <%= cat.description %></li>
      </ul>
      <br>
    </li>

  <% end %>

</ul>

cats_99/app/views/cats/new.html.erb
<%= render 'form', cat: @cat, action: :new %>

cats_99/app/views/cats/show.html.erb
<table>
  <thead>
      <tr>
         <th colspan="2"> <%= @cat.name %></th>
      </tr>
  </thead>
  <tbody>
        <tr>
            <td>Attribute</td>
            <td>Value</td>
        </tr>
        <tr>
            <td>Age</td>
            <td><%= @cat.age %> years old</td>
        </tr>
        <tr>
            <td>Birth Date</td>
            <td><%= @cat.birth_date %></td>
        </tr>
        <tr>
            <td>Color</td>
            <td><%= @cat.color %></td>
        </tr>
        <tr>
            <td>Sex</td>
            <td><%= @cat.sex %></td>
        </tr>

    </tbody>
</table>

cats_99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>